-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.TESTENUM = protobuf.EnumDescriptor()
module.TESTENUM_A_ENUM = protobuf.EnumValueDescriptor()
module.TESTENUM_B_ENUM = protobuf.EnumValueDescriptor()
module.TESTENUM_C_ENUM = protobuf.EnumValueDescriptor()

module.TESTENUM_A_ENUM.name = 'a'
module.TESTENUM_A_ENUM.index = 0
module.TESTENUM_A_ENUM.number = 1
module.TESTENUM_B_ENUM.name = 'b'
module.TESTENUM_B_ENUM.index = 1
module.TESTENUM_B_ENUM.number = 2
module.TESTENUM_C_ENUM.name = 'c'
module.TESTENUM_C_ENUM.index = 2
module.TESTENUM_C_ENUM.number = 3
module.TESTENUM.name = 'TestEnum'
module.TESTENUM.full_name = '.Test.TestEnum'
module.TESTENUM.values = {TESTENUM_A_ENUM,TESTENUM_B_ENUM,TESTENUM_C_ENUM}

module.TestEnum = {}
module.TestEnum.a = 1
module.TestEnum.b = 2
module.TestEnum.c = 3


module.MESSAGE_TYPES = {}
module.ENUM_TYPES = {'TestEnum'}

return module
